name: tooltip
archived: false
friendlyId: 'tooltip_tcdqy30v6w'
type: WEB
status: PUBLISHED
icon: 'icon-web-Analytics'
defaultTemplate: false
render: true
tags:
  - Source Control
customTemplate: true
